#165273591 Comment edit history
andela/ah-backend-dojo pull request #41
Opened 2019-05-09 16:02 UTC by JamesMudidi

#### What does this PR do?
- Sets up a way to view the history of the edited comment

#### Description of Task to be completed?
- When a comment has been edited, the user can go back and view all the history of the original version of the comment before it was edited

#### How should this be manually tested?
- When a comment has been edited, hit `http:127.0.0.1/api/articles/<article slug>/comments/<comment id>/history` endpoint to view all the edited comments

#### What are the relevant pivotal tracker stories?
- [165273591](https://www.pivotaltracker.com/story/show/165273591)

#### Screenshots (if appropriate)
<img width="1440" alt="Screenshot 2019-05-09 at 6 56 28 PM" src="https://user-images.githubusercontent.com/39102955/57467967-3c0d4000-728c-11e9-97af-c8dab9c4e0ac.png">

2019-05-10 05:58 UTC, bisonlou requested changes
Great work. However, endeavour to use pylint.

2019-05-10 05:58 UTC, bisonlou commented on authors/apps/comments/serializers.py
> +from .models import (Comment,CommentLikeDislike,CommentEditHistory)
Please use pylint. If you do, there would be spaces after the commas.

2019-05-10 10:36 UTC, nadralia requested changes
NiceWork so far @JamesMudidi and @llwasampijja but let the comment history be attached to a specific comment. For now if i pass any id , it retrieve every comment history. you guys can also check out `[django-simple-history](https://pypi.org/project/django-simple-history/)` it's a library that you can use for history of models.

2019-05-10 10:49 UTC, kalsmic commented on authors/apps/comments/models.py
> +    "Model for collecting edited history of the comments"
Also consider using triple quotes for docstrings.

2019-05-10 12:19 UTC, ZackAtama approved these changes
Good work @JamesMudidi  and @llwasampijja, am all okay with this PR soon as you've implemented requested changes from @bisonlou and @nadralia.

2019-05-10 12:31 UTC, kalsmic approved these changes
Well done @llwasampijja, now a comment history is attached to a specific comment. Also, the docstring format has been corrected.

2019-05-10 14:29 UTC, nadralia approved these changes

2019-05-11 06:33 UTC, bisonlou approved these changes

2019-05-13 07:19 UTC, merged