#165936869 - Allow admin to delete a reported article
andela/ah-backend-dojo pull request #44
Opened 2019-05-13 15:12 UTC by llwasampijja

#### What does this PR do?
Allows admin to delete an article that has been reported.
#### Description of Task to be completed?
If an article is reported, it is upon to the admins of the site to investigate the allegations. If it is discovered that the allegations have some merit, then the admin can set the report_status to resolved and then delete the article in question.
#### What are the relevant pivotal tracker stories?
[#165936869](https://www.pivotaltracker.com/story/show/165936869)

2019-05-14 13:01 UTC, kalsmic requested changes
@llwasampijja, well done, Just make these few updates on the tests and the grammar

2019-05-14 13:01 UTC, kalsmic commented on authors/apps/articles/views.py
> +                return Response({"message": "Reported article has been deleted successfullyice"})
Please correct the grammar error. `
Response({"message": "Reported article has been deleted successfully"})

2019-05-14 13:01 UTC, kalsmic commented on authors/apps/articles/tests/test_articles_crud.py
> +        self.assertEqual(response.status_code, 200)
It would also be nice to know the kind of response the users receive besides the status code. Please consider testing for the data as well.

2019-05-15 04:23 UTC, kalsmic commented on authors/apps/articles/views.py
> +                article.delete()
@llwasampijja, What do you think about doing a soft delete for a reported article so that the author can still view the article?

2019-05-15 10:44 UTC, kalsmic approved these changes

2019-05-15 11:34 UTC, nadralia approved these changes
Nice Work

2019-05-15 12:23 UTC, JamesMudidi approved these changes
@llwasampijja Nicework

2019-05-15 12:30 UTC, merged