ft(notifications): add feature for more notifications
andela/ah-backend-dojo pull request #45
Opened 2019-05-14 05:59 UTC by AtamaZack

#### What does this PR do?
- Adds a feature to notify an author when a user follows them.
- Adds a feature to notify an author when a user likes their article.
- Adds a feature to notify an author when a user favorites their article.

#### Description of the task to be completed?
- When a user follows an author, the author receives a notification.
- When a user likes an article, the author of that article receives a notification.
- When a user favorites an article, the author of that article receives a notification.

#### What are the relevant pivotal tracker stories
- [#165936718](https://www.pivotaltracker.com/story/show/165936718)

2019-05-14 15:26 UTC, nadralia approved these changes
Nice work @AtamaZack

2019-05-15 06:04 UTC, kalsmic requested changes

2019-05-15 06:04 UTC, kalsmic commented on authors/apps/notifications/models.py
> +            instance.following.username
well done @AtamaZack, I have tested out the three instances for receiving notifications that you specified in the PR description and they work fine. However, I would think that the view button should refer back to the follower.
<img width="728" alt="Screenshot 2019-05-15 at 09 01 51" src="https://user-images.githubusercontent.com/24764476/57751982-1d75d180-76f0-11e9-9e2f-411c73db1a27.png">

2019-05-15 06:43 UTC, AtamaZack commented on authors/apps/notifications/models.py
> +            instance.following.username
@kalsmic, thanks for the feedback, resolved!

2019-05-15 06:53 UTC, bisonlou approved these changes
Well done @AtamaZack

2019-05-15 11:47 UTC, kalsmic approved these changes

2019-05-15 12:32 UTC, llwasampijja approved these changes
nice work @AtamaZack

2019-05-15 13:17 UTC, merged