#165965300 Social authentication refactor
andela/ah-backend-dojo pull request #48
Opened 2019-05-15 14:32 UTC by JamesMudidi

#### What does this PR do?
- Refactor Social Authentication

#### Description of Task to be completed?
- Refactor the authentication password to contain a random password

#### How should this be manually tested?
After cloning the repository,

- Navigate into it and install the dependencies using `pip3 install -r requirements.txt`
- Setup a database with PostgreSQL
- Set up your environment variables following the sample.env file provided and then run `source .env`
- Make migrations using `python manage.py makemigrations`
- Appl the migrations using `python manage.py migrate`
- Run the application using `python3 manage.py runserver`
- Create a developer account on any of the social media platforms supported
- Start postman and access the desired endpoint using `http://127.0.0.1:8000/api/auth/<social platform>/`. where <social platform> can be facebook
- Generate and copy the token from the already created developer account of the desired social platform eg. facebook
- use the token as shown in the screenshot below

#### Any background context you want to provide?
- After doing more research on the social auth feature, we decided to have a random password for the users
- This feature works with third-party Apis so you need to have some knowledge on the use of those Apis before proceeding to test the feature. The links below will help you get started with creating an account to become a developer for Facebook and Google where you can generate tokens and test the API.
- [Facebook](https://developers.facebook.com/)
- [Google](https://developers.google.com/oauthplayground/)

#### Screenshots

Facebook Screenshoot
<img width="1440" alt="Screenshot 2019-05-07 at 12 11 40 PM" src="https://user-images.githubusercontent.com/39102955/57288114-94441680-70c1-11e9-967c-234c0ae149f5.png">

Google ScreenShoot
<img width="1440" alt="Screenshot 2019-05-07 at 12 13 15 PM" src="https://user-images.githubusercontent.com/39102955/57288146-a0c86f00-70c1-11e9-9ee3-c29aaf7a2df9.png">

#### What are the relevant pivotal tracker stories?
[165965300](https://www.pivotaltracker.com/story/show/165965300)

2019-05-15 15:01 UTC, nadralia commented on authors/apps/authentication/social.py
> +    password = User.objects.make_random_password()
Nice Work @JamesMudidi could you specify the length/allowed chars of the password like
` passwrod = User.objects.make_random_password(length=14, allowed_chars="abcdefghjkmnpqrstuvwxyz01234567889") # zvk0hawf8m6394,

2019-05-15 15:17 UTC, nadralia approved these changes

2019-05-15 15:19 UTC, llwasampijja approved these changes
Tested the feature and works well on heroku, nice work @JamesMudidi

2019-05-16 08:44 UTC, bisonlou submitted a review, later dismissed
Well done

2019-05-16 08:44 UTC, bisonlou commented on authors/apps/authentication/social.py
>          current_user.save()
Great work @JamesMudidi. However, I wonder why we have to re-save the user if he/she already exists?

2019-05-16 11:15 UTC, kalsmic requested changes

2019-05-16 11:15 UTC, kalsmic commented on authors/apps/authentication/social.py
>          current_user = User.objects.get(email=email)
@JamesMudidi, on registration, if the user already exists simply get the token from the user object.
```
token = current_user.token
return token
```
Replace lines 20 to 25

2019-05-16 12:05 UTC, kalsmic approved these changes

2019-05-16 12:14 UTC, merged